//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soba()
        {
            this.Prijava_kvara = new HashSet<Prijava_kvara>();
            this.Rezervacijas = new HashSet<Rezervacija>();
        }
    
        public int broj_sobe { get; set; }
        public string OIB_hotela { get; set; }
        public string velicina_sobe { get; set; }
        public int kapacitet { get; set; }
        public string sadrzaj_sobe { get; set; }
        public string sadrzaj_kupaonice { get; set; }
        public string napomene { get; set; }
        public byte status { get; set; }
        public byte parkiraliste { get; set; }
        public byte[] slika_sobe { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prijava_kvara> Prijava_kvara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
    }
}
