//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gost()
        {
            this.Prijava_kvara = new HashSet<Prijava_kvara>();
            this.Recenzijas = new HashSet<Recenzija>();
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Upits = new HashSet<Upit>();
        }
    
        public int OIB_gosta { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string IBAN { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
        public string adresa { get; set; }
        public string drzavljanstvo { get; set; }
        public byte covid_test { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prijava_kvara> Prijava_kvara { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recenzija> Recenzijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Upit> Upits { get; set; }
    }
}
