//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izvjesca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izvjesca()
        {
            this.Izvjesce_sadrzi = new HashSet<Izvjesce_sadrzi>();
        }
    
        public int id_izvjesca { get; set; }
        public int OIB_zaposlenika { get; set; }
        public System.DateTime vrijeme_od { get; set; }
        public System.DateTime vrijeme_do { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izvjesce_sadrzi> Izvjesce_sadrzi { get; set; }
    }
}
