//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Popravio_kvar
    {
        public int id_prijava { get; set; }
        public int OIB_zaposlenika { get; set; }
        public System.DateTime datum_popravka { get; set; }
        public System.TimeSpan vrijeme_trajanja { get; set; }
        public decimal cijena { get; set; }
    
        public virtual Prijava_kvara Prijava_kvara { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
