//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recenzija
    {
        public int id_recenzija { get; set; }
        public int OIB_gosta { get; set; }
        public int broj_sobe { get; set; }
        public System.DateTime datum_recenzije { get; set; }
        public System.TimeSpan vrijeme_recenzije { get; set; }
        public string opis { get; set; }
        public int ocjena { get; set; }
    
        public virtual Gost Gost { get; set; }
    }
}
