//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervacija()
        {
            this.Izvjesce_sadrzi = new HashSet<Izvjesce_sadrzi>();
        }
    
        public int rezervacija_id { get; set; }
        public int broj_sobe { get; set; }
        public int OIB_gosta { get; set; }
        public System.DateTime datum_rezervacije { get; set; }
        public System.DateTime datum_dolaska { get; set; }
        public System.DateTime datum_odlaska { get; set; }
        public byte placeno { get; set; }
        public decimal cijena { get; set; }
    
        public virtual Gost Gost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izvjesce_sadrzi> Izvjesce_sadrzi { get; set; }
        public virtual Soba Soba { get; set; }
    }
}
