//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izvjesce_sadrzi
    {
        public int rezervacija_id { get; set; }
        public int id_izvjesca { get; set; }
        public System.DateTime vrijeme_kreiranja { get; set; }
    
        public virtual Izvjesca Izvjesca { get; set; }
        public virtual Rezervacija Rezervacija { get; set; }
    }
}
