//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_faza_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijava_kvara
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prijava_kvara()
        {
            this.Popravio_kvar = new HashSet<Popravio_kvar>();
        }
    
        public int id_prijava { get; set; }
        public int broj_sobe { get; set; }
        public int OIB_gosta { get; set; }
        public System.DateTime datum_prijave_kvara { get; set; }
        public string opis { get; set; }
    
        public virtual Gost Gost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popravio_kvar> Popravio_kvar { get; set; }
        public virtual Soba Soba { get; set; }
    }
}
